### ISSUE TITLE
Automated deployment using GitHub Pages

### ISSUE THREAD

**Issue by chartgerink** [bertelsmannstift/data-knowledge-hub#1]
Hi :wave: I really like this project, thanks for making it open source! 🥳 

I do not see information on how the production version is deployed, and I wonder if this is automated? In other words, if changes are made in this repository, will they show up on `data-knowledge-hub.com`? If this is a manual process right now, I would be happy to contribute a way to automate this. 

I looked around the repository a bit and ran the development version on my computer, which helped me understand how this project is deployed. I found it you use Docusaurus (nice!), which [provides a way to deploy a static website to GitHub Pages](https://docusaurus.io/docs/deployment#deploying-to-github-pages). I am sure we could find a way to automate updates to the website when the `main` branch is updated (if desirable).

I am opening this issue for your consideration and would be happy to discuss it. If it is not something you want, feel free to close the issue without a response as well. In any case, thanks for your work 😊

**Comment by cathleenberger** [comment]
Thank you so much for joining in and super happy to welcome you here!  🥳

Automated updates would be a great feature. There are a couple of things I need to check before moving this forward (including as to whether this might already be lined up) but will get back to you as soon as I can. ☺️
